apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags-volume
  namespace: airflow-cluster1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: airflow-cluster1-azure-storage-secret
    shareName: dvpairflowstoragedags103
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
