# NOTE:
# Fill in values that are printed when ./azure/scripts/storage-init.sh is run
apiVersion: v1
kind: Secret
metadata:
  name: airflow-cluster1-azure-storage-secret
  namespace: airflow-cluster1
stringData:
  # Storage account name
  azurestorageaccountname: "xx"
  # Storage account key
  azurestorageaccountkey: "xx"
